### ISSUE TITLE
host Make failed

### ISSUE THREAD

**Issue by ayamir** [alexherbo2/webextension-shell#2]
The output is:
shards build --release
make: shards: No such file or directory
make: *** [Makefile:26: build] Error 127

System:
Gentoo/Linux x86_64

Docker version 20.10.0-dev, build 831ebeae96

Crystal 0.36.0 (2021-01-30)

LLVM: 11.0.1
Default target: x86_64-pc-linux-gnu

**Comment by alexherbo2** [comment]
Do you have [Crystal] and [Shards] installed?

[Crystal]: https://crystal-lang.org
[Shards]: https://crystal-lang.org/reference/the_shards_command/

**Comment by ayamir** [comment]
> Do you have [Crystal](https://crystal-lang.org) and [Shards](https://crystal-lang.org/reference/the_shards_command/) installed?

Sorry, Shards is not installed. (Shards is not mentioned in your readme btw.)
But when I installed them all, I encounterd a new error like this:
![image](https://user-images.githubusercontent.com/61657399/106545003-81cf6900-6543-11eb-8775-12f2a29ef822.png)

Shards version:
Shards 0.13.0 (2021-01-21)
Crystal version:
Crystal 0.36.0 (2021-02-02)
LLVM: 11.0.1
Default target: x86_64-pc-linux-gnu

**Comment by alexherbo2** [comment]
I was using the `0.34` version.  `JSON.mapping` has been deprecated in favor of `JSON::Serializable` since `0.35` and removed in `0.36`.

- https://crystal-lang.org/api/0.34.0/JSON.html
- https://crystal-lang.org/api/0.35.0/JSON.html
- https://crystal-lang.org/api/0.36.0/JSON.html

**Comment by alexherbo2** [comment]
@ayamir I’m not at my home to fix the issue right now.  For the time being, you can edit the [`shard.yml`] with an explicit Crystal version:

``` yaml
crystal: 0.35.0
```

[`shard.yml`]: https://github.com/alexherbo2/webextension-shell/blob/master/host/shard.yml
